version: '3'
services:
  next:
    image: cookierocket/doodling-front 
    container_name: "doodling-front"
    restart: "on-failure"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3060:3060"