version: '3'
services:
  next:
    image: kapable/doodling-front 
    environment:
      GA_TRACKING_ID: ${GA_TRACKING_ID}
    container_name: "doodling-front"
    restart: "on-failure"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3060:3060"